version: "3.8"
networks:
  int_network:
    name: int_network

services:
  db_tor_ip:
    container_name: "postgres_db_torip"
    image: postgres:12
    restart: always
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data
    ports:
      - 5437:5432
    networks: [ int_network ]

  app:
    container_name: "tor_ip_fetcher"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db_tor_ip
    networks: [ int_network ]
    entrypoint: ["/docker-entrypoint.sh"]
